image: docker:18.09.8

cache:
  paths:
    - node_modules/

stages:
  - build

before_script:
  - export DOCKER_TAG=${CI_COMMIT_REF_NAME}
  - export IMAGE_NAME="react"
  - export COMMIT_SHORT=`echo ${CI_COMMIT_SHA} | cut -c1-8`

build:
  stage: build
  only:
    - tags
  tags:
    - shell
  script:
    - sed -i s/COMMIT_PLACEHOLDER/${COMMIT_SHORT}/ Dockerfile
    - sed -i s/TAG_PLACEHOLDER/${CI_COMMIT_REF_NAME}/ Dockerfile
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${DOCKER_TAG} .
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${DOCKER_TAG}
